# Generated by Django 5.2.9 on 2026-01-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child1', models.CharField(blank=True, choices=[('None', 'None'), ('Low', 'Low'), ('High', 'High')], max_length=10, null=True, verbose_name='Child 1')),
                ('child2', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes')], max_length=10, null=True, verbose_name='Child 2')),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Diagnosis: ')),
            ],
        ),
    ]
